name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    uses: NearlyTRex/Workflows/.github/workflows/python-ci.yml@765a25c08b845e12087b32a969dc11d5896f8e0e # v0.2.0
    permissions:
      contents: read
    with:
      commands: fitlog check data

  lint:
    uses: NearlyTRex/Workflows/.github/workflows/lint.yml@765a25c08b845e12087b32a969dc11d5896f8e0e # v0.2.0
    permissions:
      contents: read
