name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    name: Python
    uses: NearlyTRex/Workflows/.github/workflows/python-ci.yml@5afc5d2c4f534e1fb7daa83a4df2808063c8fa08 # v0.2.1
    permissions:
      contents: read
    with:
      commands: fitlog check data

  lint:
    name: Lint
    uses: NearlyTRex/Workflows/.github/workflows/lint.yml@5afc5d2c4f534e1fb7daa83a4df2808063c8fa08 # v0.2.1
    permissions:
      contents: read
